apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: gcr.io/google-samples/gb-frontend
    newName: nginx
    newTag: alpine
